CREATE TABLE [dbo].[Reports_Staging] (
    [Record #] NVARCHAR(MAX) NULL,
    [Record Type] NVARCHAR(MAX) NULL,
    [Applicant Name] NVARCHAR(MAX) NULL,
    [Date Submitted] NVARCHAR(MAX) NULL,
    [Address] NVARCHAR(MAX) NULL,
    [Record Status] NVARCHAR(MAX) NULL,
    [Applicant Email] NVARCHAR(MAX) NULL,
    [Third Ticket Notes for Administrative Staff] NVARCHAR(MAX) NULL,
    [Applicant PhoneNo] NVARCHAR(MAX) NULL,
    [Archived] NVARCHAR(MAX) NULL,
    [Building Type] NVARCHAR(MAX) NULL,
    [Change Request Sent Date] NVARCHAR(MAX) NULL,
    [City] NVARCHAR(MAX) NULL,
    [Country] NVARCHAR(MAX) NULL,
    [Date Draft Started] NVARCHAR(MAX) NULL,
    [Date Last Re-submitted] NVARCHAR(MAX) NULL,
    [Department] NVARCHAR(MAX) NULL,
    [Expiration Date] NVARCHAR(MAX) NULL,
    [Historical Permit No] NVARCHAR(MAX) NULL,
    [Is Historical] NVARCHAR(MAX) NULL,
    [Is Renewal] NVARCHAR(MAX) NULL,
    [Last Record Activity] NVARCHAR(MAX) NULL,
    [Latitude] NVARCHAR(MAX) NULL,
    [Location] NVARCHAR(MAX) NULL,
    [Location Flags] NVARCHAR(MAX) NULL,
    [Location ID] NVARCHAR(MAX) NULL,
    [Longitude] NVARCHAR(MAX) NULL,
    [Lot Area] NVARCHAR(MAX) NULL,
    [MAT ID] NVARCHAR(MAX) NULL,
    [Mblac] NVARCHAR(MAX) NULL,
    [Owner Country] NVARCHAR(MAX) NULL,
    [Number of Versions] NVARCHAR(MAX) NULL,
    [Occupancy Type] NVARCHAR(MAX) NULL,
    [Number of Locations] NVARCHAR(MAX) NULL,
    [Owner City] NVARCHAR(MAX) NULL,
    [Owner Email] NVARCHAR(MAX) NULL,
    [Owner Name] NVARCHAR(MAX) NULL,
    [Owner Postal Code] NVARCHAR(MAX) NULL,
    [Owner Phone No] NVARCHAR(MAX) NULL,
    [Owner Street Name] NVARCHAR(MAX) NULL,
    [Owner State] NVARCHAR(MAX) NULL,
    [Owner Street No] NVARCHAR(MAX) NULL,
    [Owner Unit] NVARCHAR(MAX) NULL,
    [Permit/License Issued Date] NVARCHAR(MAX) NULL,
    [Postal Code] NVARCHAR(MAX) NULL,
    [Project Label] NVARCHAR(MAX) NULL,
    [Project Name] NVARCHAR(MAX) NULL,
    [Property Use] NVARCHAR(MAX) NULL,
    [Renewal #] NVARCHAR(MAX) NULL,
    [Renewal Submitted] NVARCHAR(MAX) NULL,
    [Segment End Point Latitude] NVARCHAR(MAX) NULL,
    [Segment End Address] NVARCHAR(MAX) NULL,
    [Segment End Point Longitude] NVARCHAR(MAX) NULL,
    [Segment Length (miles)] NVARCHAR(MAX) NULL,
    [Segment Start Address] NVARCHAR(MAX) NULL,
    [Segment Start Point Latitude] NVARCHAR(MAX) NULL,
    [Segment Start Point Longitude] NVARCHAR(MAX) NULL,
    [Sewage] NVARCHAR(MAX) NULL,
    [State] NVARCHAR(MAX) NULL,
    [Street Name] NVARCHAR(MAX) NULL,
    [Submitted Online] NVARCHAR(MAX) NULL,
    [Street No] NVARCHAR(MAX) NULL,
    [Total Paid] NVARCHAR(MAX) NULL,
    [Unit] NVARCHAR(MAX) NULL,
    [User Flags] NVARCHAR(MAX) NULL,
    [Waiting on Changes] NVARCHAR(MAX) NULL,
    [Water] NVARCHAR(MAX) NULL,
    [Year Built] NVARCHAR(MAX) NULL,
    [Zoning] NVARCHAR(MAX) NULL
);